"use client";

import { useEffect, useRef, useState } from "react";
import type { ProjectVideo as ProjectVideoData } from "@/data/projects";
import { shouldAutoplayVideo } from "@/lib/video-policy";

interface ProjectVideoProps {
  video: ProjectVideoData;
}

export function ProjectVideo({ video }: ProjectVideoProps) {
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(true);
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const mediaQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
    const updatePreference = () => setPrefersReducedMotion(mediaQuery.matches);

    updatePreference();
    mediaQuery.addEventListener("change", updatePreference);

    return () => mediaQuery.removeEventListener("change", updatePreference);
  }, []);

  const shouldAutoplay = shouldAutoplayVideo(
    video.autoPlay ?? false,
    prefersReducedMotion,
  );

  useEffect(() => {
    const element = videoRef.current;
    if (!element) return;

    if (shouldAutoplay) {
      void element.play().catch(() => {
        // Native controls and the poster remain available if autoplay is blocked.
      });
    } else {
      element.pause();
      element.currentTime = 0;
    }
  }, [shouldAutoplay]);

  return (
    <div className="mt-7 overflow-hidden rounded-lg border border-[#e7e7e7] bg-black shadow-[0_18px_50px_rgba(0,0,0,0.08)]">
      <video
        ref={videoRef}
        className="block h-auto w-full focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-3px] focus-visible:outline-white"
        src={video.src}
        poster={video.poster}
        aria-label={video.label}
        autoPlay={shouldAutoplay}
        loop={video.loop}
        muted={video.muted ?? true}
        controls={video.controls ?? true}
        playsInline
        preload="metadata"
      >
        Your browser does not support embedded video. The poster image shows the
        KYNEXA robotics demo generated by Scroll Wizard.
      </video>
    </div>
  );
}